# Rust Format
#
# A formatting tool that enforces the standard Rust-community code style.
# rustfmt doc - https://rust-lang.github.io/rustfmt/
# ---

# Specifies which edition is used by the parser.
edition = "2021"
# Maximum width of each line
max_width = 85
# Use tab characters for indentation, spaces for alignment
hard_tabs = false
# Number of spaces per tab
tab_spaces = 4
# Reorder import and extern crate statements alphabetically in groups (a group is separated by a newline).
reorder_imports = true
# Controls how imports are structured in use statements.
imports_granularity = "Crate"
# Controls the strategy for how consecutive imports are grouped together.
group_imports = "StdExternalCrate"
# Reorder mod declarations alphabetically in group.
reorder_modules = true
# Merge multiple derives into a single one.
merge_derives = true
# Use field initialize shorthand if possible.
use_field_init_shorthand = true
# Indent on expressions or items.
indent_style = "Block"
# Break comments to fit on the line
wrap_comments = true
# Maximum length of comments.
comment_width = 85
# Convert /* */ comments to // comments where possible
normalize_comments = true
